### ISSUE TITLE
Change Sponsorship section copy

### ISSUE THREAD

**Issue by sarahwohl** [makemodel/uxcamp#134]
Since we need to recruit sponsors I think we should change the copy to be more outward recruitment.

Current copy:
"Huge thanks to our amazing sponsors. This event would not be possible without them. For information about sponsorships you can email us or take a look at our prospectus."

Suggested ideas:
"This event is not possible without amazing sponsors like you, supporting our design community. If you're a company or individaul in the design or tech community and are interested in a small or large sponsorship, more information can be found in our Sponsorship Prospectus or by emailing us."

@kidfribble could use a rewrite but you get the gist.

**Comment by kidfribble** [comment]
Made a slight modification on your copy and updated. Will update again once sponsorship prospectus is finished and posted!
